version: 0.2

phases:
  install:
    commands:
      - git clone https://github.com/pyenv-win.git $HOME/ .pyenv
      - pyenv install 
      - poetry install
  pre_build:
    commands:
      - poetry run pytest
  build:
    commands:
      - poetry build
artifacts:
  files:
    - packaged.yaml
  discard-paths: yes
