version: 0.2

phases:
  install:
    commands:
      - brew install
      - pyenv install 
      - poetry install
  pre_build:
    commands:
      - poetry run pytest
  build:
    commands:
      - poetry build
artifacts:
  files:
    - packaged.yaml
  discard-paths: yes
