version: 0.2

phases:
  install:
    commands:
      - poetry add black
  pre_build:
    commands:
      - poetry run pytest
  build:
    commands:
      - poetry build
artifacts:
  files:
    - packaged.yaml
  discard-paths: yes
